// Code generated by "pkgimport -p redisstore -i gopkg.in/go-pot/sessions.v1/redisstore -o redisstore.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p redisstore -i gopkg.in/go-pot/sessions.v1/redisstore -o redisstore.go

package redisstore

import (
	origin "gopkg.in/go-pot/sessions.v1/redisstore"
)

// Declaration
var (

	// New returns a new Redis store
	NewWithDB = origin.NewWithDB

	// New returns a new Redis store
	New = origin.New
)
