// Code generated by "pkgimport -p cookiesstore -i github.com/goincremental/negroni-sessions/cookiestore -o cookiestore.go"; DO NOT EDIT.

//go:generate pkgimport -p cookiesstore -i github.com/goincremental/negroni-sessions/cookiestore -o cookiestore.go

package cookiesstore

import (
	origin "github.com/goincremental/negroni-sessions/cookiestore"
)

var (
	// function
	New = origin.New
)
