// Code generated by "pkgimport -p cookiesstore -i github.com/goincremental/negroni-sessions/cookiestore -o cookiestore.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p cookiesstore -i github.com/goincremental/negroni-sessions/cookiestore -o cookiestore.go

package cookiesstore

import (
	origin "github.com/goincremental/negroni-sessions/cookiestore"
)

var (
	// function

	/*New returns a new CookieStore.
	 */
	New = origin.New
)
