// Code generated by "pkgimport -p pot -i gopkg.in/ffmt.v1 -o ffmt.go"; DO NOT EDIT.

//go:generate pkgimport -p pot -i gopkg.in/ffmt.v1 -o ffmt.go

package pot

import (
	origin "gopkg.in/ffmt.v1"
)

var (
	// function
	Biglen         = origin.Biglen
	FMakeStack     = origin.FMakeStack
	FMakeStackFunc = origin.FMakeStackFunc
	FmtTable       = origin.FmtTable
	Format         = origin.Format
	Fp             = origin.Fp
	Fpjson         = origin.Fpjson
	Fprint         = origin.Fprint
	Fputs          = origin.Fputs
	Mark           = origin.Mark
	MarkStack      = origin.MarkStack
	MarkStackFull  = origin.MarkStackFull
	NewOptional    = origin.NewOptional
	P              = origin.P
	Pjson          = origin.Pjson
	Print          = origin.Print
	Puts           = origin.Puts
	Sp             = origin.Sp
	Spjson         = origin.Spjson
	Sprint         = origin.Sprint
	Sputs          = origin.Sputs
	ToTable        = origin.ToTable
)

var (
	// value
	BigWord            = origin.BigWord
	CanDefaultString   = origin.CanDefaultString
	CanFilterDuplicate = origin.CanFilterDuplicate
	CanRowSpan         = origin.CanRowSpan
	Printf             = origin.Printf
	Println            = origin.Println
	Space              = origin.Space
	StlyeP             = origin.StlyeP
	StlyePjson         = origin.StlyePjson
	StlyePrint         = origin.StlyePrint
	StlyePuts          = origin.StlyePuts
)
