// Code generated by "pkgimport -p pot -i github.com/urfave/negroni -o negroni.go";

// Already edited

////go:generate pkgimport -p pot -i github.com/urfave/negroni -o negroni.go

package pot

import (
	origin "github.com/urfave/negroni"
)

type (
	// type
	Handler        = origin.Handler
	HandlerFunc    = origin.HandlerFunc
	Negroni        = origin.Negroni
	Recovery       = origin.Recovery
	ResponseWriter = origin.ResponseWriter
)

var (
	// function
	New      = origin.New
	Wrap     = origin.Wrap
	WrapFunc = origin.WrapFunc
)

var (
	// value
	DefaultAddress = origin.DefaultAddress
)
