// Code generated by "pkgimport -p pot -i github.com/unrolled/render -o render.go"; DO NOT EDIT.

//go:generate pkgimport -p pot -i github.com/unrolled/render -o render.go

package pot

import (
	origin "github.com/unrolled/render"
)

type (
	// type
	Render = origin.Render
)

var (
	// function
	NewRender = origin.New
)
