// Code generated by "pkgimport -p router -i github.com/gorilla/mux -o mux.go"; DO NOT EDIT.

//go:generate pkgimport -p router -i github.com/gorilla/mux -o mux.go

package router

import (
	origin "github.com/gorilla/mux"
)

type (
	// type
	BuildVarsFunc = origin.BuildVarsFunc
	MatcherFunc   = origin.MatcherFunc
	Route         = origin.Route
	RouteMatch    = origin.RouteMatch
	Router        = origin.Router
	WalkFunc      = origin.WalkFunc
)

var (
	// function
	CurrentRoute = origin.CurrentRoute
	NewRouter    = origin.NewRouter
	Vars         = origin.Vars
)

var (
	// value
	ErrMethodMismatch = origin.ErrMethodMismatch
	ErrNotFound       = origin.ErrNotFound
	SkipRouter        = origin.SkipRouter
)
