// Code generated by "pkgimport -p sessions -i gopkg.in/go-pot/sessions.v1 -o sessions.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p sessions -i gopkg.in/go-pot/sessions.v1 -o sessions.go

package sessions

import (
	origin "gopkg.in/go-pot/sessions.v1"
)

// type
type (

	// TokenGetSetter allows you to save and retrieve a value stored in a cookie
	TokenGetSetter = origin.TokenGetSetter

	// Store is an interface for custom session stores.
	Store = origin.Store

	// Session stores the values and optional configuration for a session.
	Session = origin.Session

	// Options stores configuration for a session or session store.
	//
	// Fields are a subset of http.Cookie fields.
	Options = origin.Options
)

// Declaration
var (

	// Sessions is a Middleware that maps a session.Session service into the negroni handler chain.
	// Sessions can use a number of storage solutions with the given store.
	Sessions = origin.Sessions

	// NewCookieToken returns the default TokenGetSetter
	NewCookieToken = origin.NewCookieToken

	// GetSession returns the session stored in the request context
	GetSession = origin.GetSession

	ErrInvalidModified = origin.ErrInvalidModified

	ErrInvalidId = origin.ErrInvalidId
)
