// Code generated by "pkgimport -p sessions -i github.com/goincremental/negroni-sessions -o sessions.go"; DO NOT EDIT.

//go:generate pkgimport -p sessions -i github.com/goincremental/negroni-sessions -o sessions.go

package sessions

import (
	origin "github.com/goincremental/negroni-sessions"
)

type (
	// type
	Options        = origin.Options
	Session        = origin.Session
	Store          = origin.Store
	TokenGetSetter = origin.TokenGetSetter
)

var (
	// function
	GetSession     = origin.GetSession
	NewCookieToken = origin.NewCookieToken
	Sessions       = origin.Sessions
)

var (
	// value
	ErrInvalidId       = origin.ErrInvalidId
	ErrInvalidModified = origin.ErrInvalidModified
)
