// Code generated by "pkgimport -p sessions -i github.com/goincremental/negroni-sessions -o sessions.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p sessions -i github.com/goincremental/negroni-sessions -o sessions.go

package sessions

import (
	origin "github.com/goincremental/negroni-sessions"
)

type (
	// type

	Store = origin.Store

	Options = origin.Options

	Session = origin.Session

	TokenGetSetter = origin.TokenGetSetter
)

var (
	// function

	/*Sessions is a Middleware that maps a session.Session service into the negroni handler chain.
	Sessions can use a number of storage solutions with the given store.
	*/
	Sessions = origin.Sessions

	/*GetSession returns the session stored in the request context
	 */
	GetSession = origin.GetSession

	/*NewCookieToken returns the default TokenGetSetter
	 */
	NewCookieToken = origin.NewCookieToken
)

var (
	// value

	ErrInvalidId = origin.ErrInvalidId

	ErrInvalidModified = origin.ErrInvalidModified
)
