// Code generated by "pkgimport -p orm -i github.com/go-xorm/xorm -o orm.go"; DO NOT EDIT.

//go:generate pkgimport -p orm -i github.com/go-xorm/xorm -o orm.go

package orm

import (
	origin "github.com/go-xorm/xorm"
)

type (
	// type
	AfterDeleteProcessor      = origin.AfterDeleteProcessor
	AfterInsertProcessor      = origin.AfterInsertProcessor
	AfterLoadProcessor        = origin.AfterLoadProcessor
	AfterLoadSessionProcessor = origin.AfterLoadSessionProcessor
	AfterSetProcessor         = origin.AfterSetProcessor
	AfterUpdateProcessor      = origin.AfterUpdateProcessor
	BeforeDeleteProcessor     = origin.BeforeDeleteProcessor
	BeforeInsertProcessor     = origin.BeforeInsertProcessor
	BeforeSetProcessor        = origin.BeforeSetProcessor
	BeforeUpdateProcessor     = origin.BeforeUpdateProcessor
	Cell                      = origin.Cell
	DiscardLogger             = origin.DiscardLogger
	Engine                    = origin.Engine
	EngineGroup               = origin.EngineGroup
	EngineInterface           = origin.EngineInterface
	GroupPolicy               = origin.GroupPolicy
	GroupPolicyHandler        = origin.GroupPolicyHandler
	Interface                 = origin.Interface
	IterFunc                  = origin.IterFunc
	LRUCacher                 = origin.LRUCacher
	MemoryStore               = origin.MemoryStore
	Rows                      = origin.Rows
	Session                   = origin.Session
	SimpleLogger              = origin.SimpleLogger
	Statement                 = origin.Statement
	Table                     = origin.Table
	TableName                 = origin.TableName
)

var (
	// function
	AutoIncrTagHandler     = origin.AutoIncrTagHandler
	CacheTagHandler        = origin.CacheTagHandler
	CommentTagHandler      = origin.CommentTagHandler
	CreatedTagHandler      = origin.CreatedTagHandler
	DefaultTagHandler      = origin.DefaultTagHandler
	DeletedTagHandler      = origin.DeletedTagHandler
	ExtendsTagHandler      = origin.ExtendsTagHandler
	IgnoreTagHandler       = origin.IgnoreTagHandler
	IndexTagHandler        = origin.IndexTagHandler
	LeastConnPolicy        = origin.LeastConnPolicy
	LocalTagHandler        = origin.LocalTagHandler
	NULLTagHandler         = origin.NULLTagHandler
	NewEngine              = origin.NewEngine
	NewEngineGroup         = origin.NewEngineGroup
	NewLRUCacher           = origin.NewLRUCacher
	NewLRUCacher2          = origin.NewLRUCacher2
	NewMemoryStore         = origin.NewMemoryStore
	NewSimpleLogger        = origin.NewSimpleLogger
	NewSimpleLogger2       = origin.NewSimpleLogger2
	NewSimpleLogger3       = origin.NewSimpleLogger3
	NoCacheTagHandler      = origin.NoCacheTagHandler
	NotNullTagHandler      = origin.NotNullTagHandler
	OnlyFromDBTagHandler   = origin.OnlyFromDBTagHandler
	OnlyToDBTagHandler     = origin.OnlyToDBTagHandler
	PKTagHandler           = origin.PKTagHandler
	RandomPolicy           = origin.RandomPolicy
	RoundRobinPolicy       = origin.RoundRobinPolicy
	SQLTypeTagHandler      = origin.SQLTypeTagHandler
	UTCTagHandler          = origin.UTCTagHandler
	UniqueTagHandler       = origin.UniqueTagHandler
	UpdatedTagHandler      = origin.UpdatedTagHandler
	VersionTagHandler      = origin.VersionTagHandler
	WeightRandomPolicy     = origin.WeightRandomPolicy
	WeightRoundRobinPolicy = origin.WeightRoundRobinPolicy
)

var (
	// value
	DEFAULT_LOG_FLAG   = origin.DEFAULT_LOG_FLAG
	DEFAULT_LOG_LEVEL  = origin.DEFAULT_LOG_LEVEL
	DEFAULT_LOG_PREFIX = origin.DEFAULT_LOG_PREFIX
	ErrCacheFailed     = origin.ErrCacheFailed
	ErrConditionType   = origin.ErrConditionType
	ErrNeedDeletedCond = origin.ErrNeedDeletedCond
	ErrNotExist        = origin.ErrNotExist
	ErrNotImplemented  = origin.ErrNotImplemented
	ErrParamsType      = origin.ErrParamsType
	ErrTableNotFound   = origin.ErrTableNotFound
	ErrUnSupportedType = origin.ErrUnSupportedType
	Version            = origin.Version
)
