// Code generated by "pkgimport -p pot -i github.com/urfave/negroni -o recovery.go";

// Already edited

////go:generate pkgimport -p pot -i github.com/urfave/negroni -o recovery.go

package recovery

import (
	origin "github.com/urfave/negroni"
)

type (
	// type
	Recovery = origin.Recovery
)

var (
	// function
	NewRecovery = origin.NewRecovery
)
