// Code generated by "pkgimport -p cli -i gopkg.in/urfave/cli.v2 -o cli.go"; DO NOT EDIT.

//go:generate pkgimport -p cli -i gopkg.in/urfave/cli.v2 -o cli.go

package cli

import (
	origin "gopkg.in/urfave/cli.v2"
)

type (
	// type
	ActionFunc          = origin.ActionFunc
	AfterFunc           = origin.AfterFunc
	App                 = origin.App
	Args                = origin.Args
	Author              = origin.Author
	BeforeFunc          = origin.BeforeFunc
	BoolFlag            = origin.BoolFlag
	Command             = origin.Command
	CommandCategories   = origin.CommandCategories
	CommandCategory     = origin.CommandCategory
	CommandNotFoundFunc = origin.CommandNotFoundFunc
	CommandsByName      = origin.CommandsByName
	Context             = origin.Context
	DurationFlag        = origin.DurationFlag
	ErrorFormatter      = origin.ErrorFormatter
	ExitCoder           = origin.ExitCoder
	Flag                = origin.Flag
	FlagStringFunc      = origin.FlagStringFunc
	FlagsByName         = origin.FlagsByName
	Float64Flag         = origin.Float64Flag
	Float64Slice        = origin.Float64Slice
	Float64SliceFlag    = origin.Float64SliceFlag
	Generic             = origin.Generic
	GenericFlag         = origin.GenericFlag
	Int64Flag           = origin.Int64Flag
	Int64Slice          = origin.Int64Slice
	Int64SliceFlag      = origin.Int64SliceFlag
	IntFlag             = origin.IntFlag
	IntSlice            = origin.IntSlice
	IntSliceFlag        = origin.IntSliceFlag
	MultiError          = origin.MultiError
	OnUsageErrorFunc    = origin.OnUsageErrorFunc
	PathFlag            = origin.PathFlag
	Serializeder        = origin.Serializeder
	ShellCompleteFunc   = origin.ShellCompleteFunc
	StringFlag          = origin.StringFlag
	StringSlice         = origin.StringSlice
	StringSliceFlag     = origin.StringSliceFlag
	Uint64Flag          = origin.Uint64Flag
	UintFlag            = origin.UintFlag
)

var (
	// function
	DefaultAppComplete     = origin.DefaultAppComplete
	Exit                   = origin.Exit
	HandleExitCoder        = origin.HandleExitCoder
	NewContext             = origin.NewContext
	NewFloat64Slice        = origin.NewFloat64Slice
	NewInt64Slice          = origin.NewInt64Slice
	NewIntSlice            = origin.NewIntSlice
	NewStringSlice         = origin.NewStringSlice
	ShowAppHelp            = origin.ShowAppHelp
	ShowAppHelpAndExit     = origin.ShowAppHelpAndExit
	ShowCommandCompletions = origin.ShowCommandCompletions
	ShowCommandHelp        = origin.ShowCommandHelp
	ShowCommandHelpAndExit = origin.ShowCommandHelpAndExit
	ShowCompletions        = origin.ShowCompletions
	ShowSubcommandHelp     = origin.ShowSubcommandHelp
	ShowVersion            = origin.ShowVersion
)

var (
	// value
	AppHelpTemplate        = origin.AppHelpTemplate
	CommandHelpTemplate    = origin.CommandHelpTemplate
	ErrWriter              = origin.ErrWriter
	FlagStringer           = origin.FlagStringer
	GenerateCompletionFlag = origin.GenerateCompletionFlag
	HelpFlag               = origin.HelpFlag
	HelpPrinter            = origin.HelpPrinter
	HelpPrinterCustom      = origin.HelpPrinterCustom
	InitCompletionFlag     = origin.InitCompletionFlag
	OsExiter               = origin.OsExiter
	SubcommandHelpTemplate = origin.SubcommandHelpTemplate
	VersionFlag            = origin.VersionFlag
	VersionPrinter         = origin.VersionPrinter
)
