// Code generated by "pkgimport -p cli -i gopkg.in/urfave/cli.v2 -o cli.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p cli -i gopkg.in/urfave/cli.v2 -o cli.go

package cli

import (
	origin "gopkg.in/urfave/cli.v2"
)

type (
	// type

	Serializeder = origin.Serializeder

	FlagsByName = origin.FlagsByName

	Flag = origin.Flag

	Generic = origin.Generic

	StringSlice = origin.StringSlice

	IntSlice = origin.IntSlice

	Int64Slice = origin.Int64Slice

	Float64Slice = origin.Float64Slice

	ShellCompleteFunc = origin.ShellCompleteFunc

	BeforeFunc = origin.BeforeFunc

	AfterFunc = origin.AfterFunc

	ActionFunc = origin.ActionFunc

	CommandNotFoundFunc = origin.CommandNotFoundFunc

	OnUsageErrorFunc = origin.OnUsageErrorFunc

	FlagStringFunc = origin.FlagStringFunc

	Args = origin.Args

	CommandCategories = origin.CommandCategories

	CommandCategory = origin.CommandCategory

	Command = origin.Command

	CommandsByName = origin.CommandsByName

	MultiError = origin.MultiError

	ErrorFormatter = origin.ErrorFormatter

	ExitCoder = origin.ExitCoder

	App = origin.App

	Author = origin.Author

	Context = origin.Context

	BoolFlag = origin.BoolFlag

	DurationFlag = origin.DurationFlag

	Float64Flag = origin.Float64Flag

	GenericFlag = origin.GenericFlag

	Int64Flag = origin.Int64Flag

	IntFlag = origin.IntFlag

	IntSliceFlag = origin.IntSliceFlag

	Int64SliceFlag = origin.Int64SliceFlag

	Float64SliceFlag = origin.Float64SliceFlag

	StringFlag = origin.StringFlag

	PathFlag = origin.PathFlag

	StringSliceFlag = origin.StringSliceFlag

	Uint64Flag = origin.Uint64Flag

	UintFlag = origin.UintFlag
)

var (
	// function

	/*NewStringSlice creates a *StringSlice with default values
	 */
	NewStringSlice = origin.NewStringSlice

	/*NewIntSlice makes an *IntSlice with default values
	 */
	NewIntSlice = origin.NewIntSlice

	/*NewInt64Slice makes an *Int64Slice with default values
	 */
	NewInt64Slice = origin.NewInt64Slice

	/*NewFloat64Slice makes a *Float64Slice with default values
	 */
	NewFloat64Slice = origin.NewFloat64Slice

	/*ShowAppHelpAndExit - Prints the list of subcommands for the app and exits with exit code.
	 */
	ShowAppHelpAndExit = origin.ShowAppHelpAndExit

	/*ShowAppHelp is an action that displays the help.
	 */
	ShowAppHelp = origin.ShowAppHelp

	/*DefaultAppComplete prints the list of subcommands as the default app completion method
	 */
	DefaultAppComplete = origin.DefaultAppComplete

	/*ShowCommandHelpAndExit - exits with code after showing help
	 */
	ShowCommandHelpAndExit = origin.ShowCommandHelpAndExit

	/*ShowCommandHelp prints help for the given command
	 */
	ShowCommandHelp = origin.ShowCommandHelp

	/*ShowSubcommandHelp prints help for the given subcommand
	 */
	ShowSubcommandHelp = origin.ShowSubcommandHelp

	/*ShowVersion prints the version number of the App
	 */
	ShowVersion = origin.ShowVersion

	/*ShowCompletions prints the lists of commands within a given context
	 */
	ShowCompletions = origin.ShowCompletions

	/*ShowCommandCompletions prints the custom completions for a given command
	 */
	ShowCommandCompletions = origin.ShowCommandCompletions

	/*Exit wraps a message and exit code into an ExitCoder suitable for handling by
	HandleExitCoder
	*/
	Exit = origin.Exit

	/*HandleExitCoder checks if the error fulfills the ExitCoder interface, and if
	so prints the error to stderr (if it is non-empty) and calls OsExiter with the
	given exit code.  If the given error is a MultiError, then this func is
	called on all members of the Errors slice and calls OsExiter with the last exit code.
	*/
	HandleExitCoder = origin.HandleExitCoder

	/*NewContext creates a new context. For use in when invoking an App or Command action.
	 */
	NewContext = origin.NewContext
)

var (
	// value

	GenerateCompletionFlag = origin.GenerateCompletionFlag

	InitCompletionFlag = origin.InitCompletionFlag

	VersionFlag = origin.VersionFlag

	HelpFlag = origin.HelpFlag

	FlagStringer = origin.FlagStringer

	AppHelpTemplate = origin.AppHelpTemplate

	CommandHelpTemplate = origin.CommandHelpTemplate

	SubcommandHelpTemplate = origin.SubcommandHelpTemplate

	HelpPrinter = origin.HelpPrinter

	HelpPrinterCustom = origin.HelpPrinterCustom

	VersionPrinter = origin.VersionPrinter

	OsExiter = origin.OsExiter

	ErrWriter = origin.ErrWriter
)
