// Code generated by "pkgimport -p redisstore -i github.com/goincremental/negroni-sessions/redisstore -o redisstore.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p redisstore -i github.com/goincremental/negroni-sessions/redisstore -o redisstore.go

package redisstore

import (
	origin "github.com/goincremental/negroni-sessions/redisstore"
)

var (
	// function

	/*New returns a new Redis store
	 */
	New = origin.New
)
