// Code generated by "pkgimport -p redisstore -i github.com/goincremental/negroni-sessions/redisstore -o redisstore.go"; DO NOT EDIT.

//go:generate pkgimport -p redisstore -i github.com/goincremental/negroni-sessions/redisstore -o redisstore.go

package redisstore

import (
	origin "github.com/goincremental/negroni-sessions/redisstore"
)

var (
	// function
	New = origin.New
)
