// Code generated by "pkgimport -p cookiesstore -i gopkg.in/go-pot/sessions.v1/cookiestore -o cookiestore.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p cookiesstore -i gopkg.in/go-pot/sessions.v1/cookiestore -o cookiestore.go

package cookiesstore

import (
	origin "gopkg.in/go-pot/sessions.v1/cookiestore"
)

var (
	// function

	/*New returns a new CookieStore.
	 */
	New = origin.New
)
