// Code generated by "pkgimport -p cookiesstore -i gopkg.in/go-pot/sessions.v1/cookiestore -o cookiestore.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p cookiesstore -i gopkg.in/go-pot/sessions.v1/cookiestore -o cookiestore.go

package cookiesstore

import (
	origin "gopkg.in/go-pot/sessions.v1/cookiestore"
)

// Declaration
var (

	// New returns a new CookieStore.
	New = origin.New
)
