// Code generated by "pkgimport -p pot -i github.com/urfave/negroni -o static.go";

// Already edited

////go:generate pkgimport -p pot -i github.com/urfave/negroni -o static.go

package static

import (
	origin "github.com/urfave/negroni"
)

type (
	// type
	Static = origin.Static
)

var (
	// function
	NewStatic = origin.NewStatic
)
