// Code generated by "pkgimport -p pot -i github.com/urfave/negroni -o logger.go";

// Already edited

////go:generate pkgimport -p pot -i github.com/urfave/negroni -o logger.go

package logger

import (
	origin "github.com/urfave/negroni"
)

var (
	// function
	NewLogger = origin.NewLogger
)

var (
	// value
	LoggerDefaultDateFormat = origin.LoggerDefaultDateFormat
	LoggerDefaultFormat     = origin.LoggerDefaultFormat
)
