// Code generated by "pkgimport -p config -i gopkg.in/configer.v1 -o configer.go"; DO NOT EDIT.

//go:generate pkgimport -p config -i gopkg.in/configer.v1 -o configer.go

package config

import (
	origin "gopkg.in/configer.v1"
)

var (
	// function
	Load        = origin.Load
	Parse       = origin.Parse
	ProcessTags = origin.ProcessTags
	Read        = origin.Read
)
