// Code generated by "pkgimport -p config -i gopkg.in/configer.v1 -o configer.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p config -i gopkg.in/configer.v1 -o configer.go

package config

import (
	origin "gopkg.in/configer.v1"
)

var (
	// function

	Read = origin.Read

	ProcessTags = origin.ProcessTags

	Load = origin.Load

	Parse = origin.Parse
)
