// Code generated by "pkgimport -p config -i github.com/wzshiming/configer -o configer.go"; DO NOT EDIT.

//go:generate pkgimport -p config -i github.com/wzshiming/configer -o configer.go

package config

import (
	origin "github.com/wzshiming/configer"
)

var (
	// function
	Load        = origin.Load
	Parse       = origin.Parse
	ProcessTags = origin.ProcessTags
	Read        = origin.Read
)
