// Code generated by "pkgimport -p filesystemstore -i gopkg.in/go-pot/sessions.v1/filesystemstore -o filesystemstore.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p filesystemstore -i gopkg.in/go-pot/sessions.v1/filesystemstore -o filesystemstore.go

package filesystemstore

import (
	origin "gopkg.in/go-pot/sessions.v1/filesystemstore"
)

// Declaration
var (

	// New returns a new FilesystemStore.
	New = origin.New
)
