// Code generated by "pkgimport -p filesystemstore -i gopkg.in/go-pot/sessions.v1/filesystemstore -o filesystemstore.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p filesystemstore -i gopkg.in/go-pot/sessions.v1/filesystemstore -o filesystemstore.go

package filesystemstore

import (
	origin "gopkg.in/go-pot/sessions.v1/filesystemstore"
)

var (
	// function

	/*New returns a new FilesystemStore.

	 */
	New = origin.New
)
