package generate

import (
	"bytes"
	"go/format"
	"io/ioutil"
	"path"
	"strings"
	"text/template"

	"github.com/wzshiming/go-swagger/swagger"
	"github.com/wzshiming/go-swagger/swaggergen"
	"gopkg.in/pot.v1"
)

func GenerateRouter(pkg, routers, controllers, out string) error {

	if pkg == "" {
		pkg = "routers"
	}

	swagger := &swagger.Swagger{}
	swaggergen.GB(swagger, routers, controllers)

	t := "temp"
	temp := template.New(t)
	_, err := temp.Parse(mkRouter)
	if err != nil {
		return err
	}

	buf := bytes.NewBuffer(nil)
	err = temp.ExecuteTemplate(buf, "temp", map[string]interface{}{
		"Swagger":  swagger,
		"Package":  pkg,
		"Function": strings.Split(path.Base(out), ".")[0],
	})
	if err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	err = ioutil.WriteFile(out, src, 0666)
	if err != nil {
		return err
	}

	pot.Println("Generate routers")
	return nil
}

var mkRouter = `// Code generated by "pot gen rou"; DO NOT EDIT.
package {{.Package}}
{{if .Swagger.Paths}}
import (
	controllers "{{.Swagger.Extensions.Package}}"
	"net/http"

	"gopkg.in/pot.v1"
	"gopkg.in/pot.v1/router"
)

func {{.Function}}(p *pot.Pot) *router.Router {
	r := router.NewRouter()

	paths := r.PathPrefix("{{.Swagger.BasePath}}").Subrouter()

	// init controllers
	{
		{{range $k, $v := .Swagger.Paths}}
		{{with .Get}}
		paths.Methods(http.MethodGet).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Post}}
		paths.Methods(http.MethodPost).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Put}}
		paths.Methods(http.MethodPut).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Delete}}
		paths.Methods(http.MethodDelete).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Options}}
		paths.Methods(http.MethodOptions).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Head}}
		paths.Methods(http.MethodHead).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{with .Patch}}
		paths.Methods(http.MethodPatch).Path("{{.OperationID}}").HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				t := controllers.{{.Extensions.Controllers}}{}
				t.Init(p, w, r)
				t.{{.Extensions.Methods}}()
			})
		{{end}}
		{{end}}
	}
	return r
}
{{end}}
`
