// Code generated by "pkgimport -p render -i github.com/unrolled/render -o render.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p render -i github.com/unrolled/render -o render.go

package render

import (
	origin "github.com/unrolled/render"
)

type (
	// type

	Engine = origin.Engine

	Head = origin.Head

	Data = origin.Data

	HTML = origin.HTML

	JSON = origin.JSON

	JSONP = origin.JSONP

	Text = origin.Text

	XML = origin.XML

	Delims = origin.Delims

	Options = origin.Options

	HTMLOptions = origin.HTMLOptions

	Render = origin.Render

	BufferPool = origin.BufferPool
)

var (
	// function

	/*New constructs a new Render instance with the supplied options.
	 */
	New = origin.New

	/*NewBufferPool creates a new BufferPool bounded to the given size.
	 */
	NewBufferPool = origin.NewBufferPool
)

var (
	// value

	/*ContentBinary header value for binary data.
	 */
	ContentBinary = origin.ContentBinary

	/*ContentHTML header value for HTML data.
	 */
	ContentHTML = origin.ContentHTML

	/*ContentJSON header value for JSON data.
	 */
	ContentJSON = origin.ContentJSON

	/*ContentJSONP header value for JSONP data.
	 */
	ContentJSONP = origin.ContentJSONP

	/*ContentLength header constant.
	 */
	ContentLength = origin.ContentLength

	/*ContentText header value for Text data.
	 */
	ContentText = origin.ContentText

	/*ContentType header constant.
	 */
	ContentType = origin.ContentType

	/*ContentXHTML header value for XHTML data.
	 */
	ContentXHTML = origin.ContentXHTML

	/*ContentXML header value for XML data.
	 */
	ContentXML = origin.ContentXML
)
