// Code generated by "pkgimport -p negroni -i github.com/urfave/negroni -o negroni.go"; DO NOT EDIT.
// Install by "go get -u -v gopkg.in/pkgimport.v1/cmd/pkgimport";
//go:generate pkgimport -p negroni -i github.com/urfave/negroni -o negroni.go

package negroni

import (
	origin "github.com/urfave/negroni"
)

type (
	// type

	Static = origin.Static

	LoggerEntry = origin.LoggerEntry

	ALogger = origin.ALogger

	Logger = origin.Logger

	Handler = origin.Handler

	HandlerFunc = origin.HandlerFunc

	Negroni = origin.Negroni

	PanicInformation = origin.PanicInformation

	PanicFormatter = origin.PanicFormatter

	TextPanicFormatter = origin.TextPanicFormatter

	HTMLPanicFormatter = origin.HTMLPanicFormatter

	Recovery = origin.Recovery

	ResponseWriter = origin.ResponseWriter
)

var (
	// function

	/*NewStatic returns a new instance of Static
	 */
	NewStatic = origin.NewStatic

	/*NewLogger returns a new Logger instance
	 */
	NewLogger = origin.NewLogger

	/*Wrap converts a http.Handler into a negroni.Handler so it can be used as a Negroni
	middleware. The next http.HandlerFunc is automatically called after the Handler
	is executed.
	*/
	Wrap = origin.Wrap

	/*WrapFunc converts a http.HandlerFunc into a negroni.Handler so it can be used as a Negroni
	middleware. The next http.HandlerFunc is automatically called after the Handler
	is executed.
	*/
	WrapFunc = origin.WrapFunc

	/*New returns a new Negroni instance with no middleware preconfigured.
	 */
	New = origin.New

	/*Classic returns a new Negroni instance with the default middleware already
	in the stack.

	Recovery - Panic Recovery Middleware
	Logger - Request/Response Logging
	Static - Static File Serving
	*/
	Classic = origin.Classic

	/*NewRecovery returns a new instance of Recovery
	 */
	NewRecovery = origin.NewRecovery

	/*NewResponseWriter creates a ResponseWriter that wraps an http.ResponseWriter
	 */
	NewResponseWriter = origin.NewResponseWriter
)

var (
	// value

	LoggerDefaultFormat = origin.LoggerDefaultFormat

	LoggerDefaultDateFormat = origin.LoggerDefaultDateFormat

	/*DefaultAddress is used if no other is specified.
	 */
	DefaultAddress = origin.DefaultAddress
)
